In [1]:
import pandas as pd
import statsmodels.api as sm

In [2]:
# I import the file with data

flights = pd.read_csv("BOS_CUN_trips1M.csv",)

flights.head()

,messageid,tripindex,received,currency,total,tax,surcharge,source,merchant,majorcarrierid,...,refundable,triptimestamp,receiveddate,received_odate,departure_odate,return_ddate,los2,departure_dow,return_dow,includes_sns
0,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,12,1382317607,USD,631.45,123.45,0.0,Sabre,TCY,US,...,False,1382317607,20131021,2013-10-20,2014-03-14,2014-03-22,8,5,6,1
1,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,11,1382317607,USD,632.95,124.95,0.0,Sabre,TCY,US,...,False,1382317607,20131021,2013-10-20,2014-03-14,2014-03-22,8,5,6,1
2,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,10,1382317607,USD,620.95,124.95,0.0,Sabre,TCY,B6,...,False,1382317607,20131021,2013-10-20,2014-03-14,2014-03-22,8,5,6,1
3,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,9,1382317607,USD,632.95,124.95,0.0,Sabre,TCY,US,...,False,1382317607,20131021,2013-10-20,2014-03-14,2014-03-22,8,5,6,1
4,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,8,1382317607,USD,565.95,124.95,0.0,Sabre,TCY,US,...,False,1382317607,20131021,2013-10-20,2014-03-14,2014-03-22,8,5,6,1

In [11]:
# I now want to find the day of the week of departure.

flights['departure_odate'] = pd.to_datetime(flights['departure_odate'])
flights['day_of_week_dep'] = flights['departure_odate'].dt.dayofweek

days = {0:'Mon',1:'Tue',2:'Wed',3:'Thur',4:'Fri',5:'Sat',6:'Sun'}

flights['day_of_week_dep'] = flights['day_of_week_dep'].apply(lambda x: days[x])

flights.head()

,messageid,tripindex,received,currency,total,tax,surcharge,source,merchant,majorcarrierid,...,received_odate,departure_odate,return_ddate,los2,departure_dow,return_dow,includes_sns,Days before booked,Days before booked,day_of_week_dep
0,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,12,1382317607,USD,631.45,123.45,0.0,Sabre,TCY,US,...,2013-10-20,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri
1,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,11,1382317607,USD,632.95,124.95,0.0,Sabre,TCY,US,...,2013-10-20,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri
2,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,10,1382317607,USD,620.95,124.95,0.0,Sabre,TCY,B6,...,2013-10-20,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri
3,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,9,1382317607,USD,632.95,124.95,0.0,Sabre,TCY,US,...,2013-10-20,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri
4,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,8,1382317607,USD,565.95,124.95,0.0,Sabre,TCY,US,...,2013-10-20,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri

In [12]:
# I now find day of week for return date.

flights['return_ddate'] = pd.to_datetime(flights['return_ddate'])
flights['day_of_week_ret'] = flights['return_ddate'].dt.dayofweek

days = {0:'Mon',1:'Tue',2:'Wed',3:'Thur',4:'Fri',5:'Sat',6:'Sun'}

flights['day_of_week_ret'] = flights['day_of_week_ret'].apply(lambda x: days[x])

flights.head()

,messageid,tripindex,received,currency,total,tax,surcharge,source,merchant,majorcarrierid,...,departure_odate,return_ddate,los2,departure_dow,return_dow,includes_sns,Days before booked,Days before booked,day_of_week_dep,day_of_week_ret
0,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,12,1382317607,USD,631.45,123.45,0.0,Sabre,TCY,US,...,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri,Sat
1,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,11,1382317607,USD,632.95,124.95,0.0,Sabre,TCY,US,...,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri,Sat
2,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,10,1382317607,USD,620.95,124.95,0.0,Sabre,TCY,B6,...,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri,Sat
3,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,9,1382317607,USD,632.95,124.95,0.0,Sabre,TCY,US,...,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri,Sat
4,f4f57b70aaf2f56600000141d88ccbb0294a88500186aea5,8,1382317607,USD,565.95,124.95,0.0,Sabre,TCY,US,...,2014-03-14,2014-03-22,8,5,6,1,144,144,Fri,Sat

In [26]:
'''Now I want to write my model. This is a multivariate regressiom model that predicts the price based on
a number of factors such as:
cabin class (cabinclass), 
number of outbound stops (outboundstops), 
number of return stops (returnstops),
airline travelled with (majorcarrieid),
day of the week travelled on (day_of_week_dep), 
day of the week returned on (day_of_week_ret),
whether it's a refundable or a non-refundable flight (refundable),
date of departure (departure_odate),
date of return (return_ddate)
difference betweeen the departure and return (los2)
source (source)
ticketing authority (merchant)
number of seats available (availableseats).

I exclude the number of days before booked as I know this relationship is not linear (see - polynomial regression)

I will use least squares method.
I need to make sure that I all of my variables are categorical variables.'''

flights['cabinclass'] = pd.Categorical(flights.cabinclass).codes
flights['majorcarrierid'] = pd.Categorical(flights.majorcarrierid).codes
flights['day_of_week_dep'] = pd.Categorical(flights.day_of_week_dep).codes
flights['day_of_week_ret'] = pd.Categorical(flights.day_of_week_ret).codes
flights['return_ddate'] = pd.Categorical(flights.return_ddate).codes
flights['departure_odate'] = pd.Categorical(flights.departure_odate).codes
flights['refundable'] = pd.Categorical(flights.refundable).codes
flights['source'] = pd.Categorical(flights.source).codes
flights['merchant'] = pd.Categorical(flights.merchant).codes

X = flights[['cabinclass', 'outboundstops', 'returnstops', 'majorcarrierid',
            'day_of_week_dep', 'day_of_week_ret', 'return_ddate', 'departure_odate', 'refundable', 'los2',
            'source', 'availableseats', 'merchant']]
y = flights[['total']]

X1 = sm.add_constant(X)
est = sm.OLS(y, X1).fit()

est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  total   R-squared:                       0.137
Model:                            OLS   Adj. R-squared:                  0.137
Method:                 Least Squares   F-statistic:                 1.464e+04
Date:                Sun, 10 Apr 2016   Prob (F-statistic):               0.00
Time:                        18:50:10   Log-Likelihood:            -8.3878e+06
No. Observations:             1202445   AIC:                         1.678e+07
Df Residuals:                 1202431   BIC:                         1.678e+07
Df Model:                          13
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [95.0% Conf. Int.]
-----------------------------------------------------------------------------------
const             471.4040      8.037     58.651      0.000       455.651   487.157
cabinclass        245.1280      5.455     44.933      0.000       234.435   255.820
outboundstops    -109.6157      0.677   -162.031      0.000      -110.942  -108.290
returnstops      -108.4020      0.627   -172.807      0.000      -109.631  -107.173
majorcarrierid     -4.8040      0.059    -80.776      0.000        -4.921    -4.687
day_of_week_dep    -1.5904      0.134    -11.862      0.000        -1.853    -1.328
day_of_week_ret    -0.7380      0.135     -5.463      0.000        -1.003    -0.473
return_ddate      -11.2512      2.818     -3.992      0.000       -16.775    -5.727
departure_odate    11.1076      2.819      3.941      0.000         5.583    16.632
refundable        402.4551      2.943    136.727      0.000       396.686   408.224
los2               11.7652      2.819      4.174      0.000         6.241    17.290
source            270.5108      1.147    235.852      0.000       268.263   272.759
availableseats    -14.0196      0.092   -153.171      0.000       -14.199   -13.840
merchant            4.4328      0.186     23.843      0.000         4.068     4.797
==============================================================================
Omnibus:                   726434.990   Durbin-Watson:                   0.264
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         35848235.030
Skew:                           2.241   Prob(JB):                         0.00
Kurtosis:                      29.371   Cond. No.                     8.48e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
'''This is a fairly terrible model - R squared value is only 0.137.
It seems like whether the source is refundable or not has a big influence on the total price,
so does the cabin class and source. Two other big factors are number of outbound and return stops.
P values are all small (which validates the model) and t values are large (again, implying significance).
Day of the week for departure and return doesnt make a big difference.'''