In [1]:
import pandas as pd
import numpy as np

In [15]:
# I import the file with data

flights = pd.read_csv("BOS_CUN_trips1M.csv",)

flights.head()
# I also grab the column names
flights.columns

Index([u'messageid', u'tripindex', u'received', u'currency', u'total', u'tax',
       u'surcharge', u'source', u'merchant', u'majorcarrierid', u'origin',
       u'destination', u'departure', u'return', u'outbounddurationminutes',
       u'outboundstops', u'returndurationminutes', u'returnstops',
       u'availableseats', u'cabinclass', u'paxtype', u'refundable',
       u'triptimestamp', u'receiveddate', u'received_odate',
       u'departure_odate', u'return_ddate', u'los2', u'departure_dow',
       u'return_dow', u'includes_sns'],
      dtype='object')

In [49]:
# I find the mean price of a flight for different departure and return dates combinations.

best_dates = economy.groupby(['departure_odate', 'return_ddate']).mean()

# Because I'm interested in only the total price, I can just pick this column.
# I then export it to CSV so I can visualise the data in Tableau.
best_dates['total'].to_csv("bestdates.csv")

best_dates

# The visusalisation turns out to be very big and doesn't tell me much. I decided to explore the data further.

                                tripindex      received       total     tax  \
departure_odate return_ddate
2013-09-03      2013-09-05    1195.000000  1.378163e+09  550.570000  122.57
                2013-09-06    1196.000000  1.378163e+09  553.570000  125.57
                2013-09-07    1190.000000  1.378163e+09  502.570000  125.57
                2013-09-08    1199.000000  1.378163e+09  700.570000  122.57
                2013-09-09    1194.000000  1.378163e+09  549.570000  125.57
                2013-09-10    1188.000000  1.378163e+09  490.570000  125.57
                2013-09-11    1186.000000  1.378163e+09  490.570000  125.57
                2013-09-12    1192.000000  1.378163e+09  535.570000  125.57
                2013-09-13    1166.000000  1.378163e+09  490.570000  125.57
                2013-09-14    1174.000000  1.378163e+09  535.570000  125.57
                2013-09-15    1176.000000  1.378163e+09  549.570000  125.57
                2013-09-16    1167.000000  1.378163e+09  490.570000  125.57
                2013-09-17    1172.000000  1.378163e+09  535.570000  125.57
                2013-09-18    1168.000000  1.378163e+09  490.570000  125.57
2013-09-04      2013-09-06    1203.500000  1.378174e+09  553.570000  125.57
                2013-09-07    1197.500000  1.378174e+09  502.570000  125.57
                2013-09-08    1206.000000  1.378174e+09  702.070000  124.07
                2013-09-09    1201.000000  1.378174e+09  549.570000  125.57
                2013-09-10    1196.000000  1.378174e+09  490.570000  125.57
                2013-09-11    1193.500000  1.378174e+09  490.570000  125.57
                2013-09-12    1199.000000  1.378174e+09  535.570000  125.57
                2013-09-13    1194.500000  1.378174e+09  490.570000  125.57
                2013-09-14    1180.000000  1.378174e+09  535.570000  125.57
                2013-09-15    1181.500000  1.378174e+09  549.570000  125.57
                2013-09-16    1173.000000  1.378174e+09  490.570000  125.57
                2013-09-17    1178.500000  1.378174e+09  535.570000  125.57
                2013-09-18    1174.000000  1.378174e+09  490.570000  125.57
                2013-09-19    1176.500000  1.378174e+09  490.570000  125.57
2013-09-05      2013-09-07    1200.000000  1.378221e+09  482.870000  126.87
                2013-09-08    1210.666667  1.378221e+09  627.903333  122.57
...                                   ...           ...         ...     ...
2014-09-21      2014-10-06      78.000000  1.382991e+09  693.330000  225.33
                2014-10-08      27.000000  1.382991e+09  663.330000  225.33
                2014-10-09      34.000000  1.382991e+09  693.330000  225.33
                2014-10-10      35.000000  1.382991e+09  693.330000  225.33
                2014-10-11      29.000000  1.382991e+09  688.950000  220.95
                2014-10-12      30.000000  1.382991e+09  688.950000  220.95
2014-09-22      2014-09-23      41.000000  1.382991e+09  395.950000  121.95
                2014-09-24      48.000000  1.382991e+09  395.950000  121.95
                2014-09-25      42.000000  1.382991e+09  395.950000  121.95
                2014-09-26      43.000000  1.382991e+09  395.950000  121.95
                2014-09-27      49.000000  1.382991e+09  395.950000  121.95
2014-09-23      2014-09-24       7.000000  1.382991e+09  395.950000  121.95
                2014-09-25       5.000000  1.382991e+09  395.950000  121.95
                2014-09-26       6.000000  1.382991e+09  395.950000  121.95
                2014-09-27       8.000000  1.382991e+09  395.950000  121.95
                2014-09-28      11.000000  1.382991e+09  663.330000  225.33
                2014-09-29      14.000000  1.382991e+09  667.720000  229.72
                2014-10-01       9.000000  1.382991e+09  637.720000  229.72
                2014-10-02      15.000000  1.382991e+09  667.720000  229.72
                2014-10-03      16.000000  1.382991e+09  667.720000  229.72
                2014-10-04      12.000000  1.382991e+09  663.330000  225.33
                2014-10-05      13.000000  1.382991e+09  663.330000  225.33
                2014-10-06      17.000000  1.382991e+09  667.720000  229.72
                2014-10-08      10.000000  1.382991e+09  637.720000  229.72
                2014-10-09       2.000000  1.382991e+09  667.720000  229.72
                2014-10-10       3.000000  1.382991e+09  667.720000  229.72
                2014-10-11       0.000000  1.382991e+09  663.330000  225.33
                2014-10-12       1.000000  1.382991e+09  663.330000  225.33
                2014-10-13       4.000000  1.382991e+09  667.720000  229.72
2014-12-02      2014-12-09      24.500000  1.382026e+09  535.150000  124.95

                              surcharge     departure        return  \
departure_odate return_ddate
2013-09-03      2013-09-05          0.0  1.378248e+09  1.378401e+09
                2013-09-06          0.0  1.378204e+09  1.378489e+09
                2013-09-07          0.0  1.378207e+09  1.378575e+09
                2013-09-08          0.0  1.378248e+09  1.378671e+09
                2013-09-09          0.0  1.378207e+09  1.378732e+09
                2013-09-10          0.0  1.378207e+09  1.378818e+09
                2013-09-11          0.0  1.378207e+09  1.378921e+09
                2013-09-12          0.0  1.378207e+09  1.379007e+09
                2013-09-13          0.0  1.378207e+09  1.379093e+09
                2013-09-14          0.0  1.378207e+09  1.379184e+09
                2013-09-15          0.0  1.378207e+09  1.379250e+09
                2013-09-16          0.0  1.378207e+09  1.379353e+09
                2013-09-17          0.0  1.378207e+09  1.379439e+09
                2013-09-18          0.0  1.378207e+09  1.379525e+09
2013-09-04      2013-09-06          0.0  1.378289e+09  1.378489e+09
                2013-09-07          0.0  1.378289e+09  1.378575e+09
                2013-09-08          0.0  1.378288e+09  1.378671e+09
                2013-09-09          0.0  1.378289e+09  1.378732e+09
                2013-09-10          0.0  1.378289e+09  1.378818e+09
                2013-09-11          0.0  1.378289e+09  1.378921e+09
                2013-09-12          0.0  1.378289e+09  1.379007e+09
                2013-09-13          0.0  1.378289e+09  1.379093e+09
                2013-09-14          0.0  1.378289e+09  1.379184e+09
                2013-09-15          0.0  1.378289e+09  1.379250e+09
                2013-09-16          0.0  1.378289e+09  1.379353e+09
                2013-09-17          0.0  1.378289e+09  1.379439e+09
                2013-09-18          0.0  1.378289e+09  1.379525e+09
                2013-09-19          0.0  1.378289e+09  1.379616e+09
2013-09-05      2013-09-07          0.0  1.378388e+09  1.378573e+09
                2013-09-08          0.0  1.378383e+09  1.378657e+09
...                                 ...           ...           ...
2014-09-21      2014-10-06          0.0  1.411316e+09  1.412617e+09
                2014-10-08          0.0  1.411316e+09  1.412790e+09
                2014-10-09          0.0  1.411316e+09  1.412876e+09
                2014-10-10          0.0  1.411316e+09  1.412962e+09
                2014-10-11          0.0  1.411316e+09  1.413070e+09
                2014-10-12          0.0  1.411316e+09  1.413157e+09
2014-09-22      2014-09-23          0.0  1.411389e+09  1.411503e+09
                2014-09-24          0.0  1.411389e+09  1.411579e+09
                2014-09-25          0.0  1.411389e+09  1.411675e+09
                2014-09-26          0.0  1.411389e+09  1.411762e+09
                2014-09-27          0.0  1.411389e+09  1.411819e+09
2014-09-23      2014-09-24          0.0  1.411470e+09  1.411579e+09
                2014-09-25          0.0  1.411470e+09  1.411675e+09
                2014-09-26          0.0  1.411470e+09  1.411762e+09
                2014-09-27          0.0  1.411470e+09  1.411819e+09
                2014-09-28          0.0  1.411518e+09  1.411947e+09
                2014-09-29          0.0  1.411518e+09  1.412012e+09
                2014-10-01          0.0  1.411518e+09  1.412185e+09
                2014-10-02          0.0  1.411518e+09  1.412271e+09
                2014-10-03          0.0  1.411518e+09  1.412358e+09
                2014-10-04          0.0  1.411518e+09  1.412465e+09
                2014-10-05          0.0  1.411518e+09  1.412552e+09
                2014-10-06          0.0  1.411518e+09  1.412617e+09
                2014-10-08          0.0  1.411518e+09  1.412790e+09
                2014-10-09          0.0  1.411518e+09  1.412876e+09
                2014-10-10          0.0  1.411518e+09  1.412962e+09
                2014-10-11          0.0  1.411518e+09  1.413070e+09
                2014-10-12          0.0  1.411518e+09  1.413157e+09
                2014-10-13          0.0  1.411518e+09  1.413222e+09
2014-12-02      2014-12-09          0.0  1.417523e+09  1.418143e+09

                              outbounddurationminutes  outboundstops  \
departure_odate return_ddate
2013-09-03      2013-09-05                1056.000000            1.0
                2013-09-06                 530.000000            1.0
                2013-09-07                 392.000000            1.0
                2013-09-08                1056.000000            1.0
                2013-09-09                 392.000000            1.0
                2013-09-10                 392.000000            1.0
                2013-09-11                 392.000000            1.0
                2013-09-12                 392.000000            1.0
                2013-09-13                 392.000000            1.0
                2013-09-14                 392.000000            1.0
                2013-09-15                 392.000000            1.0
                2013-09-16                 392.000000            1.0
                2013-09-17                 392.000000            1.0
                2013-09-18                 392.000000            1.0
2013-09-04      2013-09-06                 467.500000            1.0
                2013-09-07                 390.000000            1.0
                2013-09-08                 560.000000            2.0
                2013-09-09                 390.000000            1.0
                2013-09-10                 390.000000            1.0
                2013-09-11                 390.000000            1.0
                2013-09-12                 390.000000            1.0
                2013-09-13                 390.000000            1.0
                2013-09-14                 390.000000            1.0
                2013-09-15                 390.000000            1.0
                2013-09-16                 390.000000            1.0
                2013-09-17                 390.000000            1.0
                2013-09-18                 390.000000            1.0
                2013-09-19                 390.000000            1.0
2013-09-05      2013-09-07                 666.666667            1.0
                2013-09-08                 473.000000            1.0
...                                               ...            ...
2014-09-21      2014-10-06                 380.000000            1.0
                2014-10-08                 380.000000            1.0
                2014-10-09                 380.000000            1.0
                2014-10-10                 380.000000            1.0
                2014-10-11                 380.000000            1.0
                2014-10-12                 380.000000            1.0
2014-09-22      2014-09-23                 480.000000            1.0
                2014-09-24                 480.000000            1.0
                2014-09-25                 480.000000            1.0
                2014-09-26                 480.000000            1.0
                2014-09-27                 480.000000            1.0
2014-09-23      2014-09-24                 422.000000            1.0
                2014-09-25                 422.000000            1.0
                2014-09-26                 422.000000            1.0
                2014-09-27                 422.000000            1.0
                2014-09-28                 970.000000            1.0
                2014-09-29                 970.000000            1.0
                2014-10-01                 970.000000            1.0
                2014-10-02                 970.000000            1.0
                2014-10-03                 970.000000            1.0
                2014-10-04                 970.000000            1.0
                2014-10-05                 970.000000            1.0
                2014-10-06                 970.000000            1.0
                2014-10-08                 970.000000            1.0
                2014-10-09                 970.000000            1.0
                2014-10-10                 970.000000            1.0
                2014-10-11                 970.000000            1.0
                2014-10-12                 970.000000            1.0
                2014-10-13                 970.000000            1.0
2014-12-02      2014-12-09                 412.820000            1.0

                              returndurationminutes  returnstops  \
departure_odate return_ddate
2013-09-03      2013-09-05               444.000000          1.0
                2013-09-06               520.000000          1.0
                2013-09-07               422.000000          1.0
                2013-09-08               463.000000          1.0
                2013-09-09               447.000000          1.0
                2013-09-10               447.000000          1.0
                2013-09-11               424.000000          1.0
                2013-09-12               654.000000          1.0
                2013-09-13               424.000000          1.0
                2013-09-14               431.000000          1.0
                2013-09-15               924.000000          1.0
                2013-09-16               424.000000          1.0
                2013-09-17               424.000000          1.0
                2013-09-18               424.000000          1.0
2013-09-04      2013-09-06               520.000000          1.0
                2013-09-07               422.000000          1.0
                2013-09-08               463.000000          1.0
                2013-09-09               447.000000          1.0
                2013-09-10               447.000000          1.0
                2013-09-11               424.000000          1.0
                2013-09-12               654.000000          1.0
                2013-09-13               424.000000          1.0
                2013-09-14               431.000000          1.0
                2013-09-15               924.000000          1.0
                2013-09-16               424.000000          1.0
                2013-09-17               424.000000          1.0
                2013-09-18               424.000000          1.0
                2013-09-19               587.000000          1.0
2013-09-05      2013-09-07               563.000000          1.0
                2013-09-08               395.666667          1.0
...                                             ...          ...
2014-09-21      2014-10-06               502.000000          1.0
                2014-10-08               502.000000          1.0
                2014-10-09               502.000000          1.0
                2014-10-10               502.000000          1.0
                2014-10-11               762.000000          1.0
                2014-10-12               762.000000          1.0
2014-09-22      2014-09-23               463.000000          1.0
                2014-09-24               545.000000          1.0
                2014-09-25               463.000000          1.0
                2014-09-26               463.000000          1.0
                2014-09-27               588.000000          1.0
2014-09-23      2014-09-24               545.000000          1.0
                2014-09-25               463.000000          1.0
                2014-09-26               463.000000          1.0
                2014-09-27               588.000000          1.0
                2014-09-28               762.000000          1.0
                2014-09-29               502.000000          1.0
                2014-10-01               502.000000          1.0
                2014-10-02               502.000000          1.0
                2014-10-03               502.000000          1.0
                2014-10-04               762.000000          1.0
                2014-10-05               762.000000          1.0
                2014-10-06               502.000000          1.0
                2014-10-08               502.000000          1.0
                2014-10-09               502.000000          1.0
                2014-10-10               502.000000          1.0
                2014-10-11               762.000000          1.0
                2014-10-12               762.000000          1.0
                2014-10-13               502.000000          1.0
2014-12-02      2014-12-09               485.760000          1.0

                              availableseats  refundable  triptimestamp  \
departure_odate return_ddate
2013-09-03      2013-09-05             -1.00         0.0   1.378163e+09
                2013-09-06             -1.00         0.0   1.378163e+09
                2013-09-07             -1.00         0.0   1.378163e+09
                2013-09-08             -1.00         0.0   1.378163e+09
                2013-09-09             -1.00         0.0   1.378163e+09
                2013-09-10             -1.00         0.0   1.378163e+09
                2013-09-11             -1.00         0.0   1.378163e+09
                2013-09-12             -1.00         0.0   1.378163e+09
                2013-09-13             -1.00         0.0   1.378163e+09
                2013-09-14             -1.00         0.0   1.378163e+09
                2013-09-15             -1.00         0.0   1.378163e+09
                2013-09-16             -1.00         0.0   1.378163e+09
                2013-09-17             -1.00         0.0   1.378163e+09
                2013-09-18             -1.00         0.0   1.378163e+09
2013-09-04      2013-09-06             -1.00         0.0   1.378174e+09
                2013-09-07             -1.00         0.0   1.378174e+09
                2013-09-08             -1.00         0.0   1.378174e+09
                2013-09-09             -1.00         0.0   1.378174e+09
                2013-09-10             -1.00         0.0   1.378174e+09
                2013-09-11             -1.00         0.0   1.378174e+09
                2013-09-12             -1.00         0.0   1.378174e+09
                2013-09-13             -1.00         0.0   1.378174e+09
                2013-09-14             -1.00         0.0   1.378174e+09
                2013-09-15             -1.00         0.0   1.378174e+09
                2013-09-16             -1.00         0.0   1.378174e+09
                2013-09-17             -1.00         0.0   1.378174e+09
                2013-09-18             -1.00         0.0   1.378174e+09
                2013-09-19             -1.00         0.0   1.378174e+09
2013-09-05      2013-09-07             -1.00         0.0   1.378221e+09
                2013-09-08             -1.00         0.0   1.378221e+09
...                                      ...         ...            ...
2014-09-21      2014-10-06             -1.00         0.0   1.382991e+09
                2014-10-08             -1.00         0.0   1.382991e+09
                2014-10-09             -1.00         0.0   1.382991e+09
                2014-10-10             -1.00         0.0   1.382991e+09

In [32]:
# I find the mean price for the different date combinations.
# I then just pick the 'total' columns as that's the only one I'm interested in.

departurebest = economy.groupby(['departure_odate', 'return_ddate']).mean()
departurebesttotal = departurebest['total']

# I then look at some statistics for the different date combinations.
departurebesttotal.describe()

# I notice that the standard deviation is pretty high at $155

count    8682.000000
mean      534.478068
std       155.885913
min       363.031132
25%       426.482274
50%       484.854911
75%       593.550429
max      1638.231290
Name: total, dtype: float64

In [48]:
# I now want to look at the date combinations below first quartile (cheapest 25% of flights)

# I want to turn this into pandas DataFrame object.
departurebesttotaldf = pd.DataFrame(departurebesttotal)
departurebesttotaldf

departurebesttotaldf[departurebesttotaldf['total'] <= 426.482274].to_csv("lowestquartileprice.csv")

departurebesttotaldf[departurebesttotaldf['total'] <= 426.482274]
# I have 2171 rows × 1 columns.
# This means that there are 2171 different date combinations that are great to travel on.
# I spit these data out to visualise them in Tableau.

                                   total
departure_odate return_ddate
2013-09-16      2013-09-19    423.970000
2013-09-21      2013-10-08    415.370000
                2013-10-09    415.370000
2013-09-23      2013-09-26    426.473279
                2013-10-01    416.382000
                2013-10-02    422.593077
                2013-10-04    418.156364
                2013-10-05    417.217619
                2013-10-29    415.370000
                2013-10-30    415.370000
2013-09-24      2013-10-02    424.576195
                2013-10-05    414.724545
                2013-10-09    413.665652
                2013-10-30    403.370000
2013-09-25      2013-09-26    419.900000
                2013-10-03    424.518276
                2013-10-04    414.439231
                2013-10-09    419.361304
                2013-10-29    403.370000
                2013-10-30    403.370000
2013-09-26      2013-10-04    420.148571
                2013-10-05    424.442000
                2013-10-09    423.132500
2013-09-27      2013-09-28    406.885000
                2013-10-03    414.011026
                2013-10-08    426.278333
                2013-10-09    415.278333
                2013-10-10    417.340833
2013-09-28      2013-09-28    392.370000
                2013-10-08    419.112308
...                                  ...
2014-09-19      2014-09-20    395.950000
                2014-09-21    395.950000
                2014-09-22    395.950000
                2014-09-23    395.950000
                2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000
2014-09-20      2014-09-21    395.950000
                2014-09-22    395.950000
                2014-09-23    395.950000
                2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000
2014-09-21      2014-09-22    397.450000
                2014-09-23    397.450000
                2014-09-24    397.450000
                2014-09-25    397.075000
                2014-09-26    397.450000
                2014-09-27    397.450000
2014-09-22      2014-09-23    395.950000
                2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000
2014-09-23      2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000

[2171 rows x 1 columns]

In [41]:
# I want to look at the minimum price and when this happens.
# The minimum is ~363, so I'm going to look at date combinations below 364.

departurebesttotaldf[departurebesttotaldf['total'] <= 364]

                                   total
departure_odate return_ddate
2014-01-15      2014-01-29    363.031132

In [45]:
# I then want to explore date combinations below $400.

departurebesttotaldf[departurebesttotaldf['total'] <= 400]

# This gives me 1121 date combinations.

                                   total
departure_odate return_ddate
2013-09-28      2013-09-28    392.370000
                2013-10-30    367.453333
2013-09-29      2013-10-30    389.870000
                2013-10-31    384.370000
                2013-11-01    384.370000
                2013-11-06    384.370000
                2013-11-07    397.547778
                2013-11-08    384.370000
2013-09-30      2013-10-29    389.870000
                2013-10-30    389.120000
                2013-11-01    384.370000
                2013-11-06    384.370000
                2013-11-07    384.370000
                2013-11-08    384.370000
2013-10-01      2013-10-03    398.970000
                2013-10-09    397.600556
                2013-10-30    390.370000
                2013-11-01    390.370000
                2013-11-20    390.370000
2013-10-02      2013-10-31    399.370000
                2013-11-01    399.370000
                2013-11-02    399.370000
2013-10-21      2013-10-31    399.999600
2013-10-27      2013-11-05    394.284828
                2013-11-06    388.497059
                2013-11-07    386.677308
                2013-11-14    399.376923
2013-10-28      2013-10-30    397.665000
                2013-11-05    394.198621
                2013-11-06    389.707692
...                                  ...
2014-09-19      2014-09-20    395.950000
                2014-09-21    395.950000
                2014-09-22    395.950000
                2014-09-23    395.950000
                2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000
2014-09-20      2014-09-21    395.950000
                2014-09-22    395.950000
                2014-09-23    395.950000
                2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000
2014-09-21      2014-09-22    397.450000
                2014-09-23    397.450000
                2014-09-24    397.450000
                2014-09-25    397.075000
                2014-09-26    397.450000
                2014-09-27    397.450000
2014-09-22      2014-09-23    395.950000
                2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000
2014-09-23      2014-09-24    395.950000
                2014-09-25    395.950000
                2014-09-26    395.950000
                2014-09-27    395.950000

[1121 rows x 1 columns]

In [46]:
# Let's try dates below $390.

departurebesttotaldf[departurebesttotaldf['total'] <= 390]

# 529 different date combinations.

                                   total
departure_odate return_ddate
2013-09-28      2013-10-30    367.453333
2013-09-29      2013-10-30    389.870000
                2013-10-31    384.370000
                2013-11-01    384.370000
                2013-11-06    384.370000
                2013-11-08    384.370000
2013-09-30      2013-10-29    389.870000
                2013-10-30    389.120000
                2013-11-01    384.370000
                2013-11-06    384.370000
                2013-11-07    384.370000
                2013-11-08    384.370000
2013-10-27      2013-11-06    388.497059
                2013-11-07    386.677308
2013-10-28      2013-11-06    389.707692
                2013-11-07    384.928431
                2013-11-08    384.928431
2013-10-29      2013-10-31    389.608909
2013-10-31      2013-11-14    387.983704
2013-11-05      2013-11-14    381.228710
                2013-11-20    386.661765
                2013-12-03    389.370000
2013-11-10      2013-11-19    388.099057
                2013-11-20    381.055385
2013-11-11      2013-11-13    388.574074
                2013-11-19    384.345273
                2013-11-20    373.954364
                2013-11-21    372.565000
                2013-11-22    375.967288
                2013-11-23    379.952222
...                                  ...
2014-05-12      2014-05-29    384.234000
2014-05-13      2014-05-14    386.834000
                2014-05-15    387.927778
                2014-05-29    386.834000
                2014-05-31    388.634000
                2014-06-03    386.834000
2014-05-18      2014-05-21    386.650000
                2014-06-03    384.234000
                2014-06-04    384.234000
                2014-06-05    385.014000
                2014-06-06    384.834000
2014-05-19      2014-05-22    386.772000
                2014-06-03    386.316667
                2014-06-05    385.014000
                2014-06-06    384.834000
2014-05-20      2014-05-21    386.834000
                2014-05-22    387.922000
                2014-06-03    387.761111
                2014-06-04    387.761111
                2014-06-05    387.614000
                2014-06-06    387.734000
2014-05-26      2014-05-29    387.650000
                2014-06-05    387.750000
                2014-06-06    388.316667
2014-05-27      2014-05-29    386.650000
                2014-06-05    386.750000
                2014-06-06    387.816667
2014-06-03      2014-06-04    386.834000
2014-08-02      2014-08-07    389.910000
2014-08-04      2014-08-07    389.910000

[529 rows x 1 columns]